# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Chris P-K
email: contact@chrispk.com
description: > # this means to ignore newlines until "baseurl:"
  Personal blog of Chris Park-Kennaby. Mostly posting my travel photography
  - shot mainly on 35mm film - on a bi-monthly basis. May also write about
  film and technology on occasion.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chrispk.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:year/:title/
author: Chris Park-Kennaby
twitter_username: chrispykay
github_username:  chrispk
instagram_username: beingchrispy
rss: rss
contact_page: true
google_analytics: UA-49230171-1
google_adsense: ca-pub-1202132740341897
# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - gulpfile.js
  - node_modules
  - git_submodules
  - README.md